<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Онлайн-викторина</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script src="confirm_fin.js"> </script>
</head>
<body>
    <topbar>
            Добро пожаловать на сайт интеллектуальной викторины
    </topbar>

    <div id="clear"></div>

    <navi>
            <table>
                <tr><td align="center"><p>Навигация по викторине:</p></td></tr>
                <tr><td align="center"><a href="question1.phtml">Вопрос 1</a></td></tr>
                <tr><td align="center"><a href="question2.phtml">Вопрос 2</a></td></tr>
                <tr><td align="center"><a href="question3.phtml">Вопрос 3</a></td></tr>
                <tr><td align="center"><a href="question4.phtml">Вопрос 4</a></td></tr>
                <tr><td align="center"><a href="question5.phtml">Вопрос 5</a></td></tr>
                <tr><td align="center"><a onclick="conf_fin('check.php')" > <u>Закончить тест</u></a></td></tr>
            </table>
    </navi>
    <content>
        <question>
        <?php
                $con=mysqli_connect('localhost','root','root','kurs_data');
                session_start();
                $res=mysqli_query($con, "SELECT ansv_5 FROM results WHERE nickname='".$_SESSION['nickname']."'");
                if($res!=false){
                    $val=mysqli_fetch_array($res);
                    switch($val[0]){
                        case 1:{
                            echo '<table>';
                            echo '<tr><td align="center"><h2>Вопрос 5</h2></td></tr>';
                            echo '<tr><td align="center"><p>Текст вопроса</p></td></tr>';
                            echo '<tr><td align="center"><form method="post" action="commit.php">';
                            echo '<input type="hidden" name="question_id" value=5>';
                            echo '<input type="hidden" name="next" value="check.php">';
                            echo '<label><input type="radio" name="ansv" value=1 checked> Ответ1 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=2> Ответ2 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=3> Ответ3 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=4> Ответ4 </input></label><br>';
                            echo '<button type="submit">Далее</button>';
                            echo '</form></td></tr>';
                            echo '</table>';
                            break;
                        }
                        case 2:{
                            echo '<table>';
                            echo '<tr><td align="center"><h2>Вопрос 5</h2></td></tr>';
                            echo '<tr><td align="center"><p>Текст вопроса</p></td></tr>';
                            echo '<tr><td align="center"><form method="post" action="commit.php">';
                            echo '<input type="hidden" name="question_id" value=5>';
                            echo '<input type="hidden" name="next" value="check.php">';
                            echo '<label><input type="radio" name="ansv" value=1> Ответ1 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=2 checked> Ответ2 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=3> Ответ3 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=4> Ответ4 </input></label><br>';
                            echo '<button type="submit">Далее</button>';
                            echo '</form></td></tr>';
                            echo '</table>';
                            break;
                        }
                        case 3:{
                            echo '<table>';
                            echo '<tr><td align="center"><h2>Вопрос 5</h2></td></tr>';
                            echo '<tr><td align="center"><p>Текст вопроса</p></td></tr>';
                            echo '<tr><td align="center"><form method="post" action="commit.php">';
                            echo '<input type="hidden" name="question_id" value=5>';
                            echo '<input type="hidden" name="next" value="check.php">';
                            echo '<label><input type="radio" name="ansv" value=1> Ответ1 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=2> Ответ2 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=3 checked> Ответ3 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=4> Ответ4 </input></label><br>';
                            echo '<button type="submit">Далее</button>';
                            echo '</form></td></tr>';
                            echo '</table>';
                            break;
                        }
                        case 4:{
                            echo '<table>';
                            echo '<tr><td align="center"><h2>Вопрос 5</h2></td></tr>';
                            echo '<tr><td align="center"><p>Текст вопроса</p></td></tr>';
                            echo '<tr><td align="center"><form method="post" action="commit.php">';
                            echo '<input type="hidden" name="question_id" value=5>';
                            echo '<input type="hidden" name="next" value="check.php">';
                            echo '<label><input type="radio" name="ansv" value=1> Ответ1 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=2> Ответ2 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=3> Ответ3 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=4 checked> Ответ4 </input></label><br>';
                            echo '<button type="submit">Далее</button>';
                            echo '</form></td></tr>';
                            echo '</table>';
                            break;
                        }
                        default:{
                            echo '<table>';
                            echo '<tr><td align="center"><h2>Вопрос 5</h2></td></tr>';
                            echo '<tr><td align="center"><p>Текст вопроса</p></td></tr>';
                            echo '<tr><td align="center"><form method="post" action="commit.php">';
                            echo '<input type="hidden" name="question_id" value=5>';
                            echo '<input type="hidden" name="next" value="check.php">';
                            echo '<label><input type="radio" name="ansv" value=1> Ответ1 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=2> Ответ2 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=3> Ответ3 </input></label><br>';
                            echo '<label><input type="radio" name="ansv" value=4> Ответ4 </input></label><br>';
                            echo '<button type="submit">Далее</button>';
                            echo '</form></td></tr>';
                            echo '</table>';
                        }
                    }
                }
                else echo "Ошибка выполнения запроса";
                
            ?>
        </question>
    </content>

    <div id="clear"></div>
    <footer>
            <autograph>
            Автор работы - Смирнов С.В., ИКПИ-15
            </autograph>
    </footer>
</body>
</html>